name: GitHub Actions Secret Example

on:
  push:
    branches: [ main ]

jobs:
  secrets-in-github-actions:
    runs-on: windows-latest

    # The Secrect Actions GitHub example has three steps
    steps:
      # Show how to print unmasked GitHub secrets to the console
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.WEBCONFIG2 }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.WEBCONFIG2}} | sed 's/./& /g'  > result.txt
          
       #Creating a file to store the result in   
      - name: Create file
        run: touch result.txt

      # Use a GitHub Actions secret variable in a bash shell
      - name: Step 2 - GitHub Action if statement (true)
        env: 
          WHO_TO_TRUST: ${{ secrets.WEBCONFIG2 }}
        if:  env.WHO_TO_TRUST == 'Secret'
        run: echo "Hey" > result.txt #echo ${{ secrets.WEBCONFIG2 }} > result.txt

      # A GitHub Actions if statement with a secret environment variable
      - name: Step 3 - Conditional GitHub Action (false)
        shell: bash
        env: 
          WHO_TO_TRUST: ${{ secrets.WEBCONFIG2 }}
        if:  env.WHO_TO_TRUST != 'TrustNobody'
        run: echo "I was wrong thinking the GitHub secret was 'TrustNobody'!"

