name: Your Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run your-script
        run: |
          # Add your script commands here
          echo "Hello, World!"

      - name: Store secret in file
        run: |
          echo ${{ secrets.WEBCONFIG }} > secret-file.txt
          # Replace 'YOUR_SECRET' with the name of your secret
          # Replace 'path/to/secret-file.txt' with the desired file paths
